version: "3.9"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  joomla:
    depends_on:
      - db
    image: joomla:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      JOOMLA_DB_HOST: db:3306
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: joomla_db
    volumes:
      - joomla_data:/var/www/html
      - ./quickstart.zip:/tmp/quickstart.zip
    entrypoint: /bin/bash -c "apt-get update && \
      chown -R www-data:www-data /var/www/html && \
      chmod -R 755 /var/www/html && \
      apache2-foreground"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: {}
  joomla_data: {}
